"""Phase 9 target reconciliation state

Revision ID: 3f4294aa5423
Revises: c2d3e4f5a6b7
Create Date: 2026-09-02 09:40:00.895466

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3f4294aa5423'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jit_reconciliation_states',
    sa.Column('grant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('synchronized', 'drifted', 'reconciling', 'failed', 'unreachable', name='reconciliation_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['jit_access_grants.id'], name=op.f('fk_jit_reconciliation_states_jit_access_grants_grant_id'), ondelete='CASCADE')
    )
    with op.batch_alter_table('jit_reconciliation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jit_reconciliation_states_status'), ['status'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_jit_reconciliation_states_grant_id'), ['grant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jit_reconciliation_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_jit_reconciliation_states_grant_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_jit_reconciliation_states_status'))

    op.drop_table('jit_reconciliation_states')
    # ### end Alembic commands ###
