"""feat(phase2): add database foundation

Revision ID: 533284645129
Revises: 84fe0ca97169
Create Date: 2026-08-11 18:29:03.569282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533284645129'
down_revision = '84fe0ca97169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('effect', sa.Enum('allow', 'deny', name='policy_effect_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_policies'))
    )
    with op.batch_alter_table('access_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_policies_name'), ['name'], unique=True)

    op.create_table('compliance_reports',
    sa.Column('report_type', sa.Enum('soc2', 'iso27001', 'custom', name='compliance_report_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_url', sa.String(length=1024), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_compliance_reports_users_generated_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_report_type'), ['report_type'], unique=False)

    op.create_table('privileged_access_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('access_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'terminated', 'expired', name='session_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('session_token_hash', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_requests.id'], name=op.f('fk_privileged_access_sessions_access_requests_access_request_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_privileged_access_sessions_resources_resource_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_privileged_access_sessions_users_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privileged_access_sessions'))
    )
    with op.batch_alter_table('privileged_access_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privileged_access_sessions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_privileged_access_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_privileged_access_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('secret_rotation_policies',
    sa.Column('vault_secret_id', sa.Uuid(), nullable=False),
    sa.Column('rotation_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_rotation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_script_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'error', name='rotation_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_secret_id'], ['vault_secrets.id'], name=op.f('fk_secret_rotation_policies_vault_secrets_vault_secret_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_rotation_policies'))
    )
    with op.batch_alter_table('secret_rotation_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_rotation_policies_next_rotation_at'), ['next_rotation_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_rotation_policies_vault_secret_id'), ['vault_secret_id'], unique=True)

    op.create_table('session_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['privileged_access_sessions.id'], name=op.f('fk_session_events_privileged_access_sessions_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_events'))
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_session_events_session_id'))

    op.drop_table('session_events')
    with op.batch_alter_table('secret_rotation_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_rotation_policies_vault_secret_id'))
        batch_op.drop_index(batch_op.f('ix_secret_rotation_policies_next_rotation_at'))

    op.drop_table('secret_rotation_policies')
    with op.batch_alter_table('privileged_access_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privileged_access_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_privileged_access_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_privileged_access_sessions_resource_id'))

    op.drop_table('privileged_access_sessions')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_generated_at'))

    op.drop_table('compliance_reports')
    with op.batch_alter_table('access_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_policies_name'))

    op.drop_table('access_policies')
    # ### end Alembic commands ###
