"""Phase 2C Add CredentialLease and CHECKED_OUT status

Revision ID: 68ff0eec529a
Revises: 911dfe68a5cb
Create Date: 2026-08-15 12:30:36.955429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ff0eec529a'
down_revision = '911dfe68a5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_leases',
    sa.Column('vault_secret_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'returned', 'expired', 'revoked', name='lease_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_requests.id'], name=op.f('fk_credential_leases_access_requests_access_request_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credential_leases_users_user_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vault_secret_id'], ['vault_secrets.id'], name=op.f('fk_credential_leases_vault_secrets_vault_secret_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_leases'))
    )
    with op.batch_alter_table('credential_leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_leases_access_request_id'), ['access_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_leases_status'), ['status'], unique=False)
        batch_op.create_index('ix_credential_leases_unique_active', ['vault_secret_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
        batch_op.create_index(batch_op.f('ix_credential_leases_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_leases_vault_secret_id'), ['vault_secret_id'], unique=False)

    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        res = conn.execute(sa.text("SELECT conname FROM pg_constraint WHERE conrelid = 'vault_secrets'::regclass AND contype = 'c';"))
        for row in res:
            op.execute(f"ALTER TABLE vault_secrets DROP CONSTRAINT {row[0]}")
        op.create_check_constraint(
            'ck_vault_secrets_secret_status_enum',
            'vault_secrets',
            sa.text("status IN ('active', 'checked_out', 'rotating', 'disabled', 'tombstoned', 'desynced', 'jit_ephemeral')")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_leases_vault_secret_id'))
        batch_op.drop_index(batch_op.f('ix_credential_leases_user_id'))
        batch_op.drop_index('ix_credential_leases_unique_active', postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_credential_leases_status'))
        batch_op.drop_index(batch_op.f('ix_credential_leases_access_request_id'))

    op.drop_table('credential_leases')

    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        res = conn.execute(sa.text("SELECT conname FROM pg_constraint WHERE conrelid = 'vault_secrets'::regclass AND contype = 'c';"))
        for row in res:
            op.execute(f"ALTER TABLE vault_secrets DROP CONSTRAINT {row[0]}")
        op.create_check_constraint(
            'ck_vault_secrets_secret_status_enum',
            'vault_secrets',
            sa.text("status IN ('active', 'rotating', 'disabled', 'tombstoned', 'desynced', 'jit_ephemeral')")
        )
    # ### end Alembic commands ###
