"""Add PAM resources fields

Revision ID: 6d9fd148900b
Revises: 4995bd054786
Create Date: 2026-08-03 18:51:59.827792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9fd148900b'
down_revision = '4995bd054786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileged_accounts',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_privileged_accounts_resources_resource_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privileged_accounts'))
    )
    with op.batch_alter_table('privileged_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privileged_accounts_resource_id'), ['resource_id'], unique=False)

    op.create_table('resource_access_policies',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('allowed_protocol', sa.String(length=50), nullable=True),
    sa.Column('allowed_time', sa.String(length=100), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('max_session_duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_access_policies_resources_resource_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_resource_access_policies_roles_role_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_access_policies'))
    )
    with op.batch_alter_table('resource_access_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_access_policies_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_access_policies_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostname_ip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('environment', sa.Enum('dev', 'test', 'staging', 'prod', name='environment_enum', native_enum=False, create_constraint=True), server_default='prod', nullable=False))
        batch_op.add_column(sa.Column('criticality', sa.Enum('low', 'medium', 'high', 'critical', name='criticality_enum', native_enum=False, create_constraint=True), server_default='medium', nullable=False))
        batch_op.add_column(sa.Column('connection_method', sa.Enum('ssh', 'rdp', 'https', 'api', 'other', name='connection_method_enum', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_resources_users_created_by'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_resources_users_owner_id'), 'users', ['owner_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resources_users_owner_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_resources_users_created_by'), type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('connection_method')
        batch_op.drop_column('criticality')
        batch_op.drop_column('environment')
        batch_op.drop_column('port')
        batch_op.drop_column('protocol')
        batch_op.drop_column('hostname_ip')

    with op.batch_alter_table('resource_access_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_access_policies_role_id'))
        batch_op.drop_index(batch_op.f('ix_resource_access_policies_resource_id'))

    op.drop_table('resource_access_policies')
    with op.batch_alter_table('privileged_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privileged_accounts_resource_id'))

    op.drop_table('privileged_accounts')
    # ### end Alembic commands ###
