"""add vault tables

Revision ID: 84fe0ca97169
Revises: 6d9fd148900b
Create Date: 2026-08-04 19:16:26.498869

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '84fe0ca97169'
down_revision = '6d9fd148900b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_secrets',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'rotating', 'disabled', 'tombstoned', name='secret_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_vault_secrets_resources_resource_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_secrets'))
    )
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_secrets_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_secrets_status'), ['status'], unique=False)

    op.create_table('vault_secret_versions',
    sa.Column('secret_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('nonce', sa.String(length=100), nullable=False),
    sa.Column('encryption_context', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_vault_secret_versions_users_created_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['secret_id'], ['vault_secrets.id'], name=op.f('fk_vault_secret_versions_vault_secrets_secret_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_secret_versions'))
    )
    with op.batch_alter_table('vault_secret_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_secret_versions_secret_id'), ['secret_id'], unique=False)

    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_vault_secrets_current_version_id', 'vault_secret_versions', ['current_version_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vault_secrets_current_version_id', type_='foreignkey')

    with op.batch_alter_table('vault_secret_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_secret_versions_secret_id'))

    op.drop_table('vault_secret_versions')
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_secrets_status'))
        batch_op.drop_index(batch_op.f('ix_vault_secrets_resource_id'))

    op.drop_table('vault_secrets')
    # ### end Alembic commands ###
