"""Initial migration

Revision ID: 8fbc37b7aa74
Revises:
Create Date: 2026-07-01 15:36:51.471321

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8fbc37b7aa74"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create PostgreSQL Enum Types if executing on PostgreSQL
    connection = op.get_bind()
    if connection.dialect.name == "postgresql":
        sa.Enum("ip", "domain", "hash", "url", name="indicator_type_enum").create(
            connection, checkfirst=True
        )
        sa.Enum("low", "medium", "high", "critical", name="threat_level_enum").create(
            connection, checkfirst=True
        )
        sa.Enum(
            "Open",
            "Investigating",
            "Contained",
            "Closed",
            "False Positive",
            name="threat_status_enum",
        ).create(connection, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("indicator", sa.String(length=255), nullable=False),
        sa.Column(
            "indicator_type",
            sa.Enum("ip", "domain", "hash", "url", name="indicator_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "threat_level",
            sa.Enum("low", "medium", "high", "critical", name="threat_level_enum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("mitre_attack", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("analyst_notes", sa.Text(), nullable=True),
        sa.Column("assigned_analyst", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "Open",
                "Investigating",
                "Contained",
                "Closed",
                "False Positive",
                name="threat_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("threats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_threats_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_threats_indicator"), ["indicator"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_threats_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_threats_threat_level"), ["threat_level"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_threats_threat_level"))
        batch_op.drop_index(batch_op.f("ix_threats_status"))
        batch_op.drop_index(batch_op.f("ix_threats_indicator"))
        batch_op.drop_index(batch_op.f("ix_threats_created_at"))

    op.drop_table("threats")

    # Drop PostgreSQL Enum Types if executing on PostgreSQL
    connection = op.get_bind()
    if connection.dialect.name == "postgresql":
        sa.Enum(name="indicator_type_enum").drop(connection, checkfirst=True)
        sa.Enum(name="threat_level_enum").drop(connection, checkfirst=True)
        sa.Enum(name="threat_status_enum").drop(connection, checkfirst=True)
    # ### end Alembic commands ###

