"""add_override_escalate_actions

Revision ID: b176b72af3cd
Revises: b3f97027c01d
Create Date: 2026-07-29 12:56:35.780310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b176b72af3cd'
down_revision = 'b3f97027c01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('permission_action_enum', type_='check')
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('create', 'read', 'update', 'delete', 'execute', 'manage', 'approve', 'reject', 'cancel', 'override', 'escalate', name='permission_action_enum', native_enum=False, create_constraint=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('permission_action_enum', type_='check')
        batch_op.alter_column('action',
               existing_type=sa.Enum('create', 'read', 'update', 'delete', 'execute', 'manage', 'approve', 'reject', 'cancel', 'override', 'escalate', name='permission_action_enum', native_enum=False, create_constraint=True),
               type_=sa.Enum('create', 'read', 'update', 'delete', 'execute', 'manage', 'approve', 'reject', 'cancel', name='permission_action_enum', native_enum=False, create_constraint=True),
               existing_nullable=False)

    # ### end Alembic commands ###
