"""add_access_requests

Revision ID: b3f97027c01d
Revises: b9e6c6b56fd6
Create Date: 2026-07-29 11:03:15.228393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f97027c01d'
down_revision = 'b9e6c6b56fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('requested_role_id', sa.Uuid(), nullable=True),
    sa.Column('requested_resource_id', sa.Uuid(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'expired', name='access_request_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='access_request_priority_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(requested_role_id IS NOT NULL) OR (requested_resource_id IS NOT NULL)', name=op.f('ck_access_requests_ck_ar_role_or_resource')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_access_requests_users_approved_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_resource_id'], ['resources.id'], name=op.f('fk_access_requests_resources_requested_resource_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], name=op.f('fk_access_requests_roles_requested_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_access_requests_users_requester_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests'))
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_request_number'), ['request_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_requests_requested_resource_id'), ['requested_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_requested_role_id'), ['requested_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_status'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requested_role_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requested_resource_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_request_number'))
        batch_op.drop_index(batch_op.f('ix_access_requests_priority'))
        batch_op.drop_index(batch_op.f('ix_access_requests_approved_by'))

    op.drop_table('access_requests')
    # ### end Alembic commands ###
