"""feat(phase2): add jit access tables

Revision ID: b84b3943a879
Revises: 533284645129
Create Date: 2026-08-11 19:13:46.465553

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b84b3943a879'
down_revision = '533284645129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jit_access_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'revoked', 'denied', name='jit_grant_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['access_requests.id'], name=op.f('fk_jit_access_grants_access_requests_approval_request_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_jit_access_grants_users_approved_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_jit_access_grants_resources_resource_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_jit_access_grants_roles_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jit_access_grants_users_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jit_access_grants'))
    )
    with op.batch_alter_table('jit_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jit_access_grants_approval_request_id'), ['approval_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jit_access_grants_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jit_access_grants_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jit_access_grants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jit_access_grants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jit_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jit_access_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_jit_access_grants_status'))
        batch_op.drop_index(batch_op.f('ix_jit_access_grants_role_id'))
        batch_op.drop_index(batch_op.f('ix_jit_access_grants_resource_id'))
        batch_op.drop_index(batch_op.f('ix_jit_access_grants_approval_request_id'))

    op.drop_table('jit_access_grants')
    # ### end Alembic commands ###
