"""Create tables

Revision ID: b9e6c6b56fd6
Revises: 8c0dc525d1c1
Create Date: 2026-07-28 22:39:00.912357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e6c6b56fd6'
down_revision = '8c0dc525d1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_code', sa.String(length=60), nullable=False),
    sa.Column('permission_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('create', 'read', 'update', 'delete', 'execute', 'manage', name='permission_action_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'retired', name='permission_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(permission_code) >= 3', name=op.f('ck_permissions_ck_permission_code_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_permission_code'), ['permission_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_permission_name'), ['permission_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_status'), ['status'], unique=False)

    op.create_table('resources',
    sa.Column('resource_code', sa.String(length=60), nullable=False),
    sa.Column('resource_name', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.Enum('application', 'database', 'server', 'network', 'cloud', 'storage', 'api', 'other', name='resource_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'retired', name='resource_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(resource_code) >= 3', name=op.f('ck_resources_ck_resource_code_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_resource_code'), ['resource_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_resources_resource_name'), ['resource_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_resources_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('role_code', sa.String(length=60), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.Column('role_type', sa.Enum('system', 'custom', name='role_type_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'retired', name='role_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(role_code) >= 3', name=op.f('ck_roles_ck_role_code_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_role_code'), ['role_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_role_name'), ['role_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_role_type'), ['role_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('manager_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'locked', 'disabled', 'archived', name='user_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('manager_user_id IS NULL OR manager_user_id <> id', name=op.f('ck_users_manager_not_self')),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_users_users_manager_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_login_at'), ['last_login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_manager_user_id'), ['manager_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_role_permissions_users_assigned_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permissions_permission_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_roles_role_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_assigned_by_user_id'), ['assigned_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_user_roles_users_assigned_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_roles_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_users_user_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_assigned_by_user_id'), ['assigned_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_assigned_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_assigned_at'))

    op.drop_table('user_roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_assigned_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_assigned_at'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_manager_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_last_login_at'))
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_status'))
        batch_op.drop_index(batch_op.f('ix_roles_role_type'))
        batch_op.drop_index(batch_op.f('ix_roles_role_name'))
        batch_op.drop_index(batch_op.f('ix_roles_role_code'))

    op.drop_table('roles')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_status'))
        batch_op.drop_index(batch_op.f('ix_resources_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resources_resource_name'))
        batch_op.drop_index(batch_op.f('ix_resources_resource_code'))

    op.drop_table('resources')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_status'))
        batch_op.drop_index(batch_op.f('ix_permissions_permission_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_permission_code'))
        batch_op.drop_index(batch_op.f('ix_permissions_action'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
