"""add_approval_workflows

Revision ID: dd217f8b8057
Revises: 0cba1f29d30e
Create Date: 2026-08-01 06:22:08.436758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd217f8b8057'
down_revision = '0cba1f29d30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('access_request_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('approval_level', sa.Enum('manager', 'security', 'system_admin', name='approval_level_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='approval_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_request_id'], ['access_requests.id'], name=op.f('fk_approval_workflows_access_requests_access_request_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_workflows_users_approver_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_workflows'))
    )
    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_workflows_access_request_id'), ['access_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_workflows_approval_level'), ['approval_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_workflows_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_workflows_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_workflows_status'))
        batch_op.drop_index(batch_op.f('ix_approval_workflows_approver_id'))
        batch_op.drop_index(batch_op.f('ix_approval_workflows_approval_level'))
        batch_op.drop_index(batch_op.f('ix_approval_workflows_access_request_id'))

    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
