import sqlalchemy as sa
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy.dialects import postgresql
import sys

ctx = MigrationContext.configure(dialect=postgresql.dialect(), opts={"as_sql": True})
op = Operations(ctx)

# This will just print the SQL generated by Alembic
t = op.create_table(
    "threats",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
        "indicator_type",
        postgresql.ENUM("ip", "domain", "hash", "url", name="indicator_type_enum", create_type=False),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("id"),
)
